black: '#000000'
red: '#f9555f'
green: '#20af89'
yellow: '#fdf029'
blue: '#589cf5'
magenta: '#934d95'
cyan: '#1e9ee6'
white: '#bbbbbb'
brightblack: '#545454'
brightred: '#fa8b8e'
brightgreen: '#34bb99'
brightyellow: '#ffff55'
brightblue: '#589cf5'
brightmagenta: '#e75598'
brightcyan: '#3978bb'
brightwhite: '#ffffff'
background: '#1c2836'
foreground: '#ffffff'
selectionbackground: '#b4d5ff'
selectionforeground: '#1c2836'
cursorforeground: '#1c2836'
cursorbackground: '#bbbbbb'
